apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deploy.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      containers:
        - name: {{.Values.deploy.container.name}}
          image: {{.Values.deploy.container.image}}
          ports:
            - containerPort: {{.Values.app.port}}
          env:
            - name: KAFKA_BROKER_ID
              value: {{.Values.deploy.container.env.KAFKA_BROKER_ID}}
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: {{.Values.deploy.container.env.KAFKA_ZOOKEEPER_CONNECT}}
            - name: KAFKA_CFG_LISTENERS
              value: {{.Values.deploy.container.env.KAFKA_CFG_LISTENERS}}
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: {{.Values.deploy.container.env.KAFKA_CFG_ADVERTISED_LISTENERS}}
            - name: ALLOW_PLAINTEXT_LISTENER
              value: {{.Values.deploy.container.env.ALLOW_PLAINTEXT_LISTENER}}