global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka