apiVersion: v1
kind: Service
metadata:
  name: {{.Values.svc.name}}
spec:
  ports:
    - port: {{.Values.app.port}}
      targetPort: {{.Values.app.port}}
      name: http
  selector:
    app: {{.Values.app.name}}