apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    app: postgres-app
spec:
  selector:
    matchLabels:
      app: postgres-app
  template:
    metadata:
      labels:
        app: postgres-app
    spec:
      containers:
        - name: postgres-containers
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: app-config
          volumeMounts:
            - name: initdb-volume
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb-volume
          configMap:
            name: init-db-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-db-config
data:
  create_database.sql: |
    CREATE DATABASE "auth-service";
    CREATE DATABASE "user-service";
    CREATE DATABASE "post-service";