app:
  name: grafana-app
  port: 3000

deploy:
  name: grafana-deploy
  container:
    name: grafana-container
    image: grafana/grafana:latest
    env:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

svc:
  name: grafana