apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configMap.name}}
  labels:
    app: {{.Values.app.name}}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'eureka-server'
        scrape_interval: 5s
        metrics_path: '/actuator/prometheus'
        eureka_sd_configs:
          - server: http://eureka-server:8761/eureka