apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configMap.name}}
data:
  create_database.sql: |
    CREATE DATABASE "auth-service";
    CREATE DATABASE "user-service";
    CREATE DATABASE "post-service";